### PR TITLE
add --append cli option

### PR DESCRIPTION
**Pull request by justin2004**
in case you want to append to existing file.

### CODE REVIEW

**Comment by justin2004** [comment]
maybe in the docs i should put a warning that if you use bnodes you are on your own! in order to prevent accidental bnode collisions i increment something in my input filename so sparql anything mints different bnode identifiers.

**Comment by enridaga** [comment]
> maybe in the docs i should put a warning that if you use bnodes you are on your own! in order to prevent accidental bnode collisions i increment something in my input filename so sparql anything mints different bnode identifiers.

The function `fx:bnode` should create consistent bnode identifiers on multiple executions. However, this may depend also on the actual serialiser.

**Comment by enridaga** [comment]
Will appending streams work with all types of serialisations? I think n-triples and turtle should be fine but, for example, JSON-LD or XML will not, as it will break the syntax. Am I getting it right?

**Comment by justin2004** [comment]
if you append more than once to a file it works with n-triples and n-quads (which is what i use it for). 

if the serialization outputs prefix lines then i don't think this will work. turtle will output the prefixes and you can't define prefixes multiple times in a file.

i am using this cli option as an alternative to SPARQL Anything's slicing. within the jvm , i am invoking `com.github.sparqlanything.cli.SPARQLAnything/main` for each slice and appending the output to a file. the speed is acceptable too. currently i can turn 29k git commits (from a repo with 20+ years of commits) into 93 million quads in 90 minutes using this method.

oh AND i get a progress bar with an ETA!   :) 
as much as I like SPARQL i've never seen a SPARQL query engine give an ETA. hehe.

**Comment by enridaga** [comment]
To support:
- Turtle (and Star...)
- N-Quads (and Star...)
- N-Triples (and Star...)
- Trig (and Star...)

**Comment by enridaga** [comment]
Also, raise an error or stop if any other format is requested.
Future work (issues to open) is to add support for tabular data output (CSV only)

**Comment by enridaga** [comment]
We can exclude this from v0.8.0 and decide later if to integrate in future releases.

**Comment by enridaga** [comment]
We can merge this in the meantime (sorry it took so much time!)

**Comment by enridaga** [comment]
OK, the pull request breaks the build on v0.9-DEV because in the meantime we changed a method signature. I guess it is easier to re-implement it following this pull request step by step.

**Comment by enridaga** [comment]
Implement in #342

**Pull request closed without merging**
