### PR TITLE
option to use an on disk graph (TDB2)

### PR DESCRIPTION
**Pull request by justin2004**
right now when we need to triplify a large file we split the file before using sparql anything. but with this option i have been able to triplify large files (e.g. csv files with several hundred thousand rows) with a small amount of memory.

with a TDB2 you can't set the default graph to be the union graph (i might ask the apache jena mailing list about this) so if you use an on disk graph you need to add `graph ?g` in your query.

we can mark this feature as experimental or decide it needs more attention before we turn it on. i just wanted to start the discussion.

### CODE REVIEW

**Comment by justin2004** [comment]
also, i'll add some tests specifically for using a TDB2 this weekend.

EDIT
it would probably be nice just to run all the tests first using the default in memory graph then run then all again using the on disk graph.

**Comment by luigi-asprino** [comment]
The PR seems fine to me.. @justin2004 could you also implement a couple of unit tests?

**Comment by enridaga** [comment]
That's great! I have one question and one request :)

The question: what happens if the TDB2 database already exists? Is it used as a cache (triplification is not repeated for the same query) or the content is overwritten? 

The request: can you move the code needed to select the appropriate DatasetGraph outside the`FacadeXGraphBuilder`? The datasetGraph implementation can be passed in `FacadeXOpExecutor#triplify`. It could go on a separate Factory class or adding a utility method to `FacadeXOpExecutor` ... WDYT?

**Comment by justin2004** [comment]
@luigi-asprino yup. my original goal was to make all the tests run 2 times (once with an in-memory graph and once with an on-disk graph) but [this](https://github.com/justin2004/sparql.anything/blob/63eb07e2782715337b277c84c4934a8d58d5e2e2/sparql-anything-model/src/main/java/com/github/sparqlanything/model/BaseFacadeXBuilder.java#L242) prevents that from being easy. but i will add some tests that account for that.


> The question: what happens if the TDB2 database already exists? Is it used as a cache (triplification is not repeated for the same query) or the content is overwritten?

@enridaga , if you attempt to triplify the same location again the subsequent invocations are faster (because the TDB2 indexes are already built). but there is no test to see if the file is already in a named graph. so there is an attempt to overwrite but there is no work to be done (but all the attempts do take some time (just not as much as the initial triplification)).

i've found that when i wanted to keep using the same named graph (like a cache) i do this:

first (which takes a while):
```
service <x-sparql-anything:>{
    fx:properties fx:location "/app/bigfile.csv" .
    fx:properties fx:ondisk "/tmp/" .
    graph ?g {?s ?p ?o .} limit 5
}
```

then i iterate on this (which is super fast):
```
service <x-sparql-anything:>{
    fx:properties fx:location "/app/smallfile.csv" .
    fx:properties fx:ondisk "/tmp/" .
    graph <file:/app/bigfile.csv#> {?s ?p ?o .}
}
```

**Comment by justin2004** [comment]
@enridaga you mean find a better place for [this](https://github.com/justin2004/sparql.anything/blob/63eb07e2782715337b277c84c4934a8d58d5e2e2/sparql-anything-model/src/main/java/com/github/sparqlanything/model/BaseFacadeXBuilder.java#L63-L102), right?

> It could go on a separate Factory class or adding a utility method to FacadeXOpExecutor .. WDYT?

i can add a utility method there. i agree it needs to be contained better.

**Comment by enridaga** [comment]
> @enridaga you mean find a better place for [this](https://github.com/justin2004/sparql.anything/blob/63eb07e2782715337b277c84c4934a8d58d5e2e2/sparql-anything-model/src/main/java/com/github/sparqlanything/model/BaseFacadeXBuilder.java#L63-L102), right?
> 
Yes, in the future, I want to move the DG out of the FX builder. 

> i've found that when i wanted to keep using the same named graph (like a cache) i do this:

What happens if you do two different queries on the same file with different options? Is the graph cleared and rewritten or there is a risk of producing messy data? I am thinking about null-string options, triple-filtering, etc ...

**Comment by justin2004** [comment]
> Is the graph cleared 

the graph is only cleared when you add `fx:properties fx:ondisk.new "true"`. maybe that should be the default?
then we could have an option `fx:properties fx:ondisk.reuse "true"` if you want the possibility of messy data.

**Comment by justin2004** [comment]
@enridaga i added some tests for the on disk graph option.

also, now, by default, the previous TDB2 will be deleted and not reused unless you specify
`fx:properties fx:ondisk.reuse "true"`. this way there is no possibility of messy data unless you want it. 


> The request: can you move the code needed to select the appropriate DatasetGraph outside theFacadeXGraphBuilder? The datasetGraph implementation can be passed in FacadeXOpExecutor#triplify

i didn't get to that yet. if you don't mind i'd like to do that in a subsequent pull request. i'd like to start using this on disk graph option on with my team so we can see if it lessens the need to split files upstream of SPARQL Anything.

**Pull request merged**
